M48
; DRILL file {KiCad 6.0.6-3a73a75311~116~ubuntu22.04.1} date Wed 27 Jul 2022 04:16:01 PM EDT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-07-27T16:16:01-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.6-3a73a75311~116~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
%
G90
G05
T1
X159.131Y-107.95
T0
M30
